CREATE TABLE IF NOT EXISTS students (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    course VARCHAR(100) NOT NULL,
    grade DOUBLE NOT NULL,
    letter_grade VARCHAR(2) NOT NULL,
    status VARCHAR(20) NOT NULL
); 